# Creating Arrays

## Importing Numpy

In [1]:
import numpy as np

<p>A key difference between an array and a list is that arrays allow you to perform vectorized operations while a list is not designed to handle vector operations. A vector operation means a function gets applied to every item in the array.</p>

In [2]:
arr1 = np.array([1,2,3])
print(arr1)

# Vector (element-wise) operations
print(arr1 * 2)
print(arr1 + 2)
print(arr1 * arr1)

[1 2 3]
[2 4 6]
[3 4 5]
[1 4 9]


In [3]:
arr1 = np.linspace(0,1, 100)
print(arr1)

[0.         0.01010101 0.02020202 0.03030303 0.04040404 0.05050505
 0.06060606 0.07070707 0.08080808 0.09090909 0.1010101  0.11111111
 0.12121212 0.13131313 0.14141414 0.15151515 0.16161616 0.17171717
 0.18181818 0.19191919 0.2020202  0.21212121 0.22222222 0.23232323
 0.24242424 0.25252525 0.26262626 0.27272727 0.28282828 0.29292929
 0.3030303  0.31313131 0.32323232 0.33333333 0.34343434 0.35353535
 0.36363636 0.37373737 0.38383838 0.39393939 0.4040404  0.41414141
 0.42424242 0.43434343 0.44444444 0.45454545 0.46464646 0.47474747
 0.48484848 0.49494949 0.50505051 0.51515152 0.52525253 0.53535354
 0.54545455 0.55555556 0.56565657 0.57575758 0.58585859 0.5959596
 0.60606061 0.61616162 0.62626263 0.63636364 0.64646465 0.65656566
 0.66666667 0.67676768 0.68686869 0.6969697  0.70707071 0.71717172
 0.72727273 0.73737374 0.74747475 0.75757576 0.76767677 0.77777778
 0.78787879 0.7979798  0.80808081 0.81818182 0.82828283 0.83838384
 0.84848485 0.85858586 0.86868687 0.87878788 0.88888889 0.89898

In [4]:
arr1 = np.random.random((3, 3))
print(arr1)

[[0.49761521 0.2491244  0.74163423]
 [0.45294283 0.44046056 0.87678196]
 [0.99719467 0.36278665 0.62794057]]


In [5]:
arr1 = np.random.randint(0, 10, (3, 3))
print(arr1)

[[6 1 1]
 [6 1 8]
 [4 2 3]]


<h3>2. Array Attributes </h3>
<p>
Each array has the following attributes:

<ul>
<li>ndim: the number of dimensions</li>
<li>shape: the size of each dimension</li>
<li>size: the total size of the array</li>
<li>dtype: the data type of the array</li>
<li>itemsize: the size (in bytes) of each array element</li>
<li>nbytes: the total size (in bytes) of the array</li>
</ul>
Run the code below and observe the output.
</p>

In [6]:
x = np.random.randint(0, 10, (3, 3))

print("ndim: ", x.ndim)
print("shape:", x.shape)
print("x size: ", x.size)
print("dtype:", x.dtype)
print("itemsize:", x.itemsize, "bytes")
print("nbytes:", x.nbytes, "bytes")

ndim:  2
shape: (3, 3)
x size:  9
dtype: int64
itemsize: 8 bytes
nbytes: 72 bytes


# Slicing

In [9]:
x1 = np.arange(10)
print(x1)

print(x1[::2])

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


## Multidimensional slicing

In [10]:
x2 = np.array([[0,1,2], [3,4,5], [6,7,8]])
print(x2)

sl = x2[:2, :2] # Extract the first two rows and two columns
print(sl)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1]
 [3 4]]


## Reshaping

In [12]:
x3 = np.arange(1,10)
print(x3)

reshaped = x3.reshape((3,3))
print(reshaped)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
grid = np.arange(16).reshape((4,4))

In [14]:
print(grid)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [15]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower, '\n')

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]] 



In [16]:
left, right = np.hsplit(grid, [2])
print(left)
print(right, '\n')

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]] 



## Mathematical Functions 

In [17]:
x = np.arange(10)

# Native arithmentic operators
print("x =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 5 =", x * 5)
print("x / 5 =", x / 5)
print("x ** 2 = ", x ** 2)
print("x % 2  = ", x % 2)

# OR we can use explicit functions, ufuncs, e.g. "add" instead of "+"
print(np.add(x, 5))
print(np.subtract(x, 5))
print(np.multiply(x, 5))
print(np.divide(x, 5))
print(np.power(x, 2))
print(np.mod(x, 2))

x = [0 1 2 3 4 5 6 7 8 9]
x + 5 = [ 5  6  7  8  9 10 11 12 13 14]
x - 5 = [-5 -4 -3 -2 -1  0  1  2  3  4]
x * 5 = [ 0  5 10 15 20 25 30 35 40 45]
x / 5 = [0.  0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8]
x ** 2 =  [ 0  1  4  9 16 25 36 49 64 81]
x % 2  =  [0 1 0 1 0 1 0 1 0 1]
[ 5  6  7  8  9 10 11 12 13 14]
[-5 -4 -3 -2 -1  0  1  2  3  4]
[ 0  5 10 15 20 25 30 35 40 45]
[0.  0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8]
[ 0  1  4  9 16 25 36 49 64 81]
[0 1 0 1 0 1 0 1 0 1]


In [18]:
theta = np.linspace(0, np.pi, 4)
print("theta      = ", theta)
print("sin(theta) = ", np.sin(theta))
print("cos(theta) = ", np.cos(theta))
print("tan(theta) = ", np.tan(theta))

theta      =  [0.         1.04719755 2.0943951  3.14159265]
sin(theta) =  [0.00000000e+00 8.66025404e-01 8.66025404e-01 1.22464680e-16]
cos(theta) =  [ 1.   0.5 -0.5 -1. ]
tan(theta) =  [ 0.00000000e+00  1.73205081e+00 -1.73205081e+00 -1.22464680e-16]


In [19]:
x = [1, 2, 3]

print("x =", x)
print("e^x =", np.exp(x))
print("2^x =", np.exp2(x))
print("3^x =", np.power(3, x))


print("ln(x) =", np.log(x))
print("log2(x) =", np.log2(x))
print("log10(x) =", np.log10(x))

x = [1, 2, 3]
e^x = [ 2.71828183  7.3890561  20.08553692]
2^x = [2. 4. 8.]
3^x = [ 3  9 27]
ln(x) = [0.         0.69314718 1.09861229]
log2(x) = [0.        1.        1.5849625]
log10(x) = [0.         0.30103    0.47712125]


In [20]:
grid = np.random.random((3, 4))
print(grid)

print("Overall sum:", grid.sum())
print("Overall Min:", grid.min())

# Row wise and column wise min
print("Column wise minimum: ", np.amin(grid, axis=0))
print("Row wise minimum: ", np.amin(grid, axis=1))

[[0.41993905 0.94051854 0.93509925 0.07023875]
 [0.8195245  0.12901539 0.00946666 0.31168008]
 [0.57245757 0.57236148 0.7234201  0.21817322]]
Overall sum: 5.721894597653649
Overall Min: 0.009466658101441983
Column wise minimum:  [0.41993905 0.12901539 0.00946666 0.07023875]
Row wise minimum:  [0.07023875 0.00946666 0.21817322]


## Comparisons and Boolean masks 

In [24]:
x = np.array([1, 2, 3, 4, 5])

print(x < 2) # less than
print(x >= 4) # greater than or equal

[ True False False False False]
[False False False  True  True]


In [29]:
np.all(x < 6)

True

In [31]:
np.count_nonzero( x % 2 == 0)

2

In [36]:
x = np.random.randint(0, 10, (3,3))
print(x)
print('\n')
print( x < 6)

print(x[x < 6])

[[5 9 4]
 [7 1 6]
 [2 1 4]]


[[ True False  True]
 [False  True False]
 [ True  True  True]]
[5 4 1 2 1 4]
